ServiceTest作成環境構築
Accel-Hack/SimpleApplication pull request #1
Opened 2023-02-17 08:40 UTC by miura-azuma

# 概要
- Serviceのテストが書けるようにした
- pom.xmlに必要な依存関係を追加
- SampleServiceSTest作成

## 開発内容
- pom.xmlにspring-boot-starter-test, jupiterを追加

## テスト内容
- 試しにSampleServiceSTestを作成して，テストが動くことを確認

## 見てほしい箇所
- 過不足ないパッケージが追加されているか

## その他
- おそらくMapperTestで必要になるであろうファイルの変更も含まれています．

2023-02-17 12:00 UTC, KKyosuke requested changes

2023-02-17 12:03 UTC, KKyosuke commented
@miura-azuma 
ジュクマでは甘くなってるけどファイル名にはImplをつけるように（Implのクラスのテストなので）
変数名にもImplをつけたい

参考までに私が書くならこう↓かな
https://github.com/Accel-Hack/SimpleApplication/blob/feature/kyosuke/20230217_ServiceTestSample/src/test/java/com/accelhack/application/simple/app/service/SampleServiceImplSTest.java

2023-02-22 09:05 UTC, miura-azuma commented
@KKyosuke 
テスト書き直したので確認お願いします．

2023-02-22 22:55 UTC, KKyosuke approved these changes

2023-02-22 22:55 UTC, merged